# Generated by Django 5.2.3 on 2025-06-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='family_photos/')),
                ('occupation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('about', models.TextField()),
            ],
        ),
    ]
