# Generated by Django 5.2.3 on 2025-06-16 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='education_gallery/')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.education')),
            ],
        ),
    ]
